[package]
name          = "fury-testing"
description   = "Utilities for testing Fury red-bank contracts"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }
keywords      = { workspace = true }

[lib]
doctest = false

[features]
astroport         = ["cw-it/astroport", "dep:astroport"]
backtraces        = ["cosmwasm-std/backtraces", "osmosis-std/backtraces"]
default           = []
osmosis-test-tube = ["cw-it/osmosis-test-tube"]

[dependencies]
anyhow                         = { workspace = true }
astroport                      = { workspace = true, optional = true }
cosmwasm-std                   = { workspace = true }
cosmwasm-schema                = { workspace = true }
ica-oracle                     = { workspace = true }
osmosis-std                    = { workspace = true }
fury-address-provider          = { workspace = true }
fury-incentives                = { workspace = true }
fury-mock-pyth                 = { workspace = true }
fury-oracle-osmosis            = { workspace = true }
fury-oracle-wasm               = { workspace = true }
fury-osmosis                   = { workspace = true }
fury-owner                     = { workspace = true }
fury-params                    = { workspace = true }
fury-red-bank                  = { workspace = true }
fury-rewards-collector-osmosis = { workspace = true }
fury-swapper-astroport         = { workspace = true }
fury-types                     = { workspace = true }
prost                          = { workspace = true }
pyth-sdk-cw                    = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-it         = { workspace = true, features = ["multi-test"] }
cw-multi-test = { workspace = true }
